Make lottery venue fields optional [DAH-722]
SFDigitalServices/sf-dahlia-web pull request #1435
Opened 2021-02-18 19:07 UTC by james-wills-sf

[DAH-722]

We're not showing the lottery venue fields, so they should be optional.

## Old behavior
Lottery section does not show the date or covid update unless Lottery_Date, Lottery_Venue, and Lottery_Street_Address are all filled in.

## New Behvaior
Lottery section shows the date + covid update if Lottery_Date is not populated, doesn't matter if venue is populated

## COVID_UPDATE=false + Lottery_Venue="String"
<img width="1104" alt="covid_update_false" src="https://user-images.githubusercontent.com/64036574/108407695-edb70000-71d8-11eb-8f9b-d0a4fc173c71.png">

## COVID_UPDATE=false + Lottery_Venue=null
<img width="1144" alt="covid_update_false_no_string" src="https://user-images.githubusercontent.com/64036574/108407682-eb54a600-71d8-11eb-8c29-826bbfcd104c.png">

## COVID_UPDATE=true + Lottery_Venue="String"
<img width="1138" alt="covid_update_true_with_string" src="https://user-images.githubusercontent.com/64036574/108407675-e859b580-71d8-11eb-8c63-e0627dd6057a.png">

## COVID_UPDATE=true + Lottery_Venue=null
<img width="1075" alt="covid_update_true_no_string" src="https://user-images.githubusercontent.com/64036574/108407668-e5f75b80-71d8-11eb-80d4-d79559c0711f.png">

2021-02-18 19:18 UTC, akegan commented
for your example for QA can you use a listing where lottery venue info isn't the covid update text just to make it easier to QA? It would generally be an address or something.

2021-02-18 19:27 UTC, james-wills-sf commented
@akegan Okay for QA use these listings for different states:

Pre lottery, No venue text: Mount sutro https://dahlia-web-full-pr-1435.herokuapp.com/listings/a0W4U00000HlyenUAB

Pre lottery, venue text is some address: Senior Automated test listing https://dahlia-web-full-pr-1435.herokuapp.com/listings/a0W0P00000GwGl3UAF

Upcoming lottery, No venue text: 1335 Folsom https://dahlia-web-full-pr-1435.herokuapp.com/listings/a0W4U00000HlubxUAB

Upcoming lottery, venue text is some address: 788 8th av https://dahlia-web-full-pr-1435.herokuapp.com/listings/a0W4U00000HltPMUAZ


I'll also add the3se to the review instructions on the ticket

2021-03-01 20:32 UTC, akegan requested changes
Looks like some listings like [1335 folsom](https://dahlia-web-full-pr-1435.herokuapp.com/listings/a0W4U00000HlubxUAB), for example, are missing the covid update info. I think my suggestion would fix it 
![image](https://user-images.githubusercontent.com/11825994/109552333-7ad64080-7a86-11eb-84d0-2c4366362407.png)

2021-03-01 20:32 UTC, akegan commented on app/assets/javascripts/listings/templates/listing/_pre_lottery_info.html.slim
> +  p.content-group_address.c-steel.skiptranslate ng-if="!$ctrl.parent.lotteryVenueAvailable()"
This logic doesn't look quite right. Seems like we want to show if we show covid update is false and lottery venue info is available. 
```suggestion
  p.content-group_address.c-steel.skiptranslate ng-if="!$ctrl.parent.showCovidUpdate && $ctrl.parent.lotteryVenueAvailable()"
```

2021-03-02 21:04 UTC, james-wills-sf commented
@akegan I was a little confused at first but I think your change fixed the "lottery results" section but the lottery section was still empty.

Just added a commit that should fix the lottery section too

2021-03-02 21:59 UTC, akegan commented
looks like now lottery venue info isn't showing for post-lottery listings even with COVID_UPDATE=false

I updated the env var on the review app and added a venue to 1335 folsom and the venue info doesn't show up
![image](https://user-images.githubusercontent.com/11825994/109720885-83e71080-7b5f-11eb-8ff9-a1a4d380c218.png)
(https://dahlia-web-full-pr-1435.herokuapp.com/listings/a0W4U00000HlubxUAB?preview=true)

It does show up on full https://dahlia-full.herokuapp.com/listings/a0W4U00000HlubxUAB?preview=true

2021-03-02 22:37 UTC, james-wills-sf commented
@akegan good catch. I wasn't passing the listing into venueInfoAvailable(). Fixed now.

2021-03-02 23:31 UTC, akegan approved these changes
Looks good to me now. thanks for making all those changes! I merged that PR that would run prod tests on hotfix branches and it looks like they're currently failing on here. not sure why

2021-03-03 01:35 UTC, james-wills-sf commented
@akegan hmm im not seeing the failures you were talking about. I'm going to go ahead and merge

2021-03-03 01:35 UTC, akegan commented
OK I don't see it anymore either! probably just needed to refresh?

2021-03-03 01:36 UTC, merged