Finalize habitat content DAH-1065
SFDigitalServices/sf-dahlia-web pull request #1575
Opened 2022-02-02 23:39 UTC by christine-sfg

DAH-1065

Update habitat listing links and content based on the handoff figma

2022-02-02 23:59 UTC, akegan requested changes
LGTM with one minor change needed.

We need to update `listings.habitat.income_range.p1` to have 82%-109.8% as the AMI range.

2022-02-02 23:59 UTC, akegan commented on app/assets/javascripts/short-form/directives/communityScreeningHeader.js.coffee
>          # FIXME: Update the habitat url
```suggestion
```

2022-02-03 00:16 UTC, christine-sfg commented
> LGTM with one minor change needed.
> 
> We need to update `listings.habitat.income_range.p1` to have 82%-109.8% as the AMI range.

I just noticed the figma has "between 89% and 109.8% AMI". Please confirm the correct values.

2022-02-03 00:27 UTC, akegan commented
82 is the correct value. 89 was a typo. Msol [confirmed in slack too](https://sfdigitalservices.slack.com/archives/CCV0019TN/p1643846189928729)

2022-02-03 01:28 UTC, akegan approved these changes
LGTM now. Just kicked off tests again 🤞

2022-02-03 01:28 UTC, akegan commented on app/assets/json/translations/locale-en.json
> +                    "p1": "To be eligible for a Habitat for Humanity Greater San Francisco home in this listing, your household income needs to be between 82% and 109.8% AMI as listed below.",
nice catch on the typo!

2022-02-03 17:09 UTC, merged