DAH-1485: Disclaimer page
SFDigitalServices/sf-dahlia-web pull request #1859
Opened 2023-06-27 22:47 UTC by cliu02

[DAH-1485](https://sfgovdt.jira.com/browse/DAH-1485)

[DAH-1485]: https://sfgovdt.jira.com/browse/DAH-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-28 19:31 UTC, jimlin-sfgov requested changes
I noticed that on the angular version of this page, the disclaimer intro text is hidden for screens smaller than the 768px breakpoint.

This is caused by the `show-for-medium-up` class here:https://github.com/SFDigitalServices/sf-dahlia-web/blob/2d41e1f0214f43ac8117263c50a1fe5d25ee6bcd/app/assets/javascripts/pages/templates/disclaimer.html.slim#L6

2023-06-28 19:35 UTC, jimlin-sfgov commented on app/javascript/pages/getAssistance/disclaimer.tsx
> +          <div className="w-full md:w-2/3" data-test-id="assistance-main-content">
Just wondering what `data-test-id` does? We're using the value `"assistance-main-content"` both here and in `AssistanceLayout.tsx`

2023-06-28 19:45 UTC, jimlin-sfgov commented
@cliu02 Sorry, I should have made my comment more clear. I meant that the React disclaimer page is not following same style behavior as the Angular disclaimer page, the behavior being that some text getting hidden when the screen gets small enough.

The Jira ticket says "Everything stays the same as Angular", so I assumed we want the hiding-text behavior from the Angular page copied over to the React page.

2023-06-28 21:42 UTC, jimlin-sfgov approved these changes
looks good!

2023-06-29 18:37 UTC, chadbrokaw-exygy approved these changes

2023-06-29 21:17 UTC, merged