DAH-1667: Styling Educator Banner
SFDigitalServices/sf-dahlia-web pull request #1932
Opened 2023-09-12 21:21 UTC by alulabeshue-sfgov

2023-09-13 22:48 UTC, jimlin-sfgov commented
Is this PR mean to address [additional feedback](https://sfgovdt.jira.com/browse/DAH-1667?focusedCommentId=75971) that was made after the first PR was already merged in?

2023-09-13 22:52 UTC, alulabeshue-sfgov commented
> Is this PR meant to address [additional feedback](https://sfgovdt.jira.com/browse/DAH-1667?focusedCommentId=75971) that was made after the first PR was already merged in?

Yes, specifically the second comment around the spacing between letters. This time I sent out a screenshot to Yindi and Bridget to get feedback before opening this PR.

2023-09-13 23:09 UTC, jimlin-sfgov requested changes

2023-09-13 23:09 UTC, jimlin-sfgov commented on app/javascript/modules/listingDetails/ListingDetailsReservedBanner.scss
> +  font-size: 13px;
The convention in our code `scss` files is to use either `rem` or `bloom-font-size` variables to for font sizes.

2023-09-14 16:23 UTC, jimlin-sfgov approved these changes
looks good!

2023-09-14 20:35 UTC, merged