DAH-1869 fix: use dayjs to handle various startTime formats
SFDigitalServices/sf-dahlia-web pull request #2014
Opened 2023-11-28 01:36 UTC by cade-exygy

Jira: https://sfgovdt.jira.com/browse/DAH-1869

# Changes
- use dayjs to convert date string to Dayjs object
- use dayjs.diff to sort dates

# Review
-Go to a Sales listing: /listings/a0W4U00000KneiUUAR?react=true
-Ensure that the open houses are correctly ordered by date and start time
-You can compare with the Angular version: /listings/a0W4U00000KneiUUAR
-You can edit the open house list in Salesforce as well to test

2023-11-28 19:42 UTC, jimlin-sfgov requested changes

2023-11-28 19:42 UTC, jimlin-sfgov commented on app/javascript/util/listingUtil.ts
> +  const customParseFormat = require("dayjs/plugin/customParseFormat")
we should stick to `import` for consistency

2023-11-28 19:43 UTC, jimlin-sfgov commented
In the future, let's hold off on merging approved PRs until they pass PA testing. That way we avoid multiple PRs per ticket, like this one.

2023-11-28 22:46 UTC, cade-exygy commented
> In the future, let's hold off on merging approved PRs until they pass PA testing. That way we avoid multiple PRs per ticket, like this one.

Fair point. We may have to adjust how we do PA. I believe PA testing is primarily done on the full instance. Also, we will have to make some tweaks to ensure that the PR deployment environment has the same vars and plugins as Full.

2023-11-28 22:51 UTC, jimlin-sfgov commented
> I believe PA testing is primarily done on the full instance

Yeah, we will have to do some tweaks before fully moving to PR instances for PA testing. For PRs that do not rely on environment vars etc., I have been commenting in the Jira ticket with the PR instance URL for PA testers to use.

2023-11-29 21:05 UTC, jimlin-sfgov approved these changes
Looks good.

The November ones are out of order, but that is because of inconsistent user input in salesforce.

The custom parsing format here handles what salesforce users _usually_ use, which is the best we can do on the front end.

2023-11-30 17:53 UTC, cade-exygy commented
> Looks good.
> 
> The November ones are out of order, but that is because of inconsistent user input in salesforce.
> 
> The custom parsing format here handles what salesforce users _usually_ use, which is the best we can do on the front end.

Awesome! Moved ticket to PA.

2023-11-30 20:20 UTC, merged