DAH-1600 use Error Boundary on HMI table
SFDigitalServices/sf-dahlia-web pull request #2024
Opened 2023-12-05 17:36 UTC by tallulahkay

[DAH-1600](https://sfgovdt.jira.com/browse/DAH-1600)

Adds an `ErrorBoundary` to the Household Maximum Income Eligibility section so that an error message shows up instead of a forever spinner.

<img width="690" alt="Screenshot 2023-12-05 at 2 37 21 PM" src="https://github.com/SFDigitalServices/sf-dahlia-web/assets/43218114/d95699b0-7e28-4b74-a917-6852c02ad7f3">

[DAH-1600]: https://sfgovdt.jira.com/browse/DAH-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-06 19:53 UTC, jimlin-sfgov requested changes

2023-12-06 19:53 UTC, jimlin-sfgov commented on app/javascript/modules/listingDetails/ListingDetailsHMITable.tsx
> -    <ListSection
I like that you pulled this out of the component, which is more in line with how other components are structured in the Eligibility section 👍

2023-12-06 19:53 UTC, jimlin-sfgov commented on app/javascript/modules/listingDetails/ListingDetailsHMITable.tsx
> +    <span>
Could we use a fragment here instead `<>...</>`, `table` elements should not be nested in `span` elements.

2023-12-06 19:53 UTC, jimlin-sfgov commented on app/javascript/modules/listingDetails/ListingDetailsEligibility.tsx
> +        {!isHabitatListing(listing) ? (
Unless there was a good reason to change, let's stick with the `{!isHabitatListing(listing) && ...` style of conditional rendering, for consistency.

2023-12-07 23:08 UTC, tallulahkay commented on app/javascript/modules/listingDetails/ListingDetailsHMITable.tsx
> +      // TODO: Log error properly
yeah this error throwing is hacky I figured we might want to handle differently later, but can delete the comments

2023-12-07 23:57 UTC, jimlin-sfgov commented on app/javascript/modules/listingDetails/ListingDetailsHMITable.tsx
> +      // TODO: Log error properly
Sounds good, we should create a Jira ticket to capture that work

2023-12-07 23:57 UTC, jimlin-sfgov approved these changes
great work!

2023-12-08 17:44 UTC, merged