feat:DAH-2238: Account Dashboard
SFDigitalServices/sf-dahlia-web pull request #2186
Opened 2024-06-04 20:47 UTC by chadbrokaw

[DAH-2338](https://sfgovdt.jira.com/browse/DAH-2338)

2024-06-11 19:40 UTC, tallulahkay requested changes
This looks good! Left one non-blocking comment, and will approve when the redirect works as expected (left a comment on the jira ticket)

2024-06-11 22:45 UTC, cade-exygy approved these changes
Except for the redirect error, testing criteria passes. Tested in PR environment.

Good to merge once redirect error is fixed (or validating it works correctly)

2024-06-11 22:45 UTC, cade-exygy commented on app/javascript/pages/account/my-account.tsx
> +    return null
Does setting the `window.location.href` execute the redirect or do we need to do something in addition here?

2024-06-11 22:50 UTC, cade-exygy commented
> Except for the redirect error, testing criteria passes. Tested in PR environment.
> 
> Good to merge once redirect error is fixed (or validating it works correctly)

Just saw updated instructions. Testing with `my-account?react=true` works!

2024-06-12 16:40 UTC, tallulahkay approved these changes
Looks good!!

2024-06-17 15:29 UTC, merged