DAH-2379: Delete app on My Applications page
SFDigitalServices/sf-dahlia-web pull request #2206
Opened 2024-07-02 00:40 UTC by cliu02

[DAH-2379](https://sfgovdt.jira.com/browse/DAH-2379)

Note: this branch includes DAH-2342. 

[DAH-2379]: https://sfgovdt.jira.com/browse/DAH-2379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-05 21:26 UTC, jimlin-sfgov commented on app/javascript/api/authApiService.ts
> +    console.log("res.data", res.data)
issue: Remove debugging statement

2024-07-05 21:26 UTC, jimlin-sfgov commented on app/javascript/components/ApplicationItem.tsx
> +export const convertToReadableDate = (dateString: string) => {
suggestion: move exportable function to a helper/utility file.

2024-07-08 23:15 UTC, tallulahkay requested changes
The success path here works! But if there's a failure to delete the application (salesforce api returns anything other than 200), you get: 
![Screenshot 2024-07-08 at 4 13 01 PM](https://github.com/SFDigitalServices/sf-dahlia-web/assets/43218114/e7ee3b37-ea69-431e-b7c8-83a92de36894)
and then when you refresh the page, you still see the application

In the angular version, failure looks like this: 
![Screenshot 2024-07-08 at 4 14 29 PM](https://github.com/SFDigitalServices/sf-dahlia-web/assets/43218114/045fd643-b5db-4084-9dfb-4cab28ba9053)

Wondering if it's been discussed with Yindi what failure should look like? I think we should aim for parity with how the angular application currently works when there is an api failure

2024-07-16 00:10 UTC, tallulahkay approved these changes
yay!!

2024-07-16 00:21 UTC, jimlin-sfgov approved these changes
@chadbrokaw Looking forward to getting https://github.com/SFDigitalServices/sf-dahlia-web/pull/2207 merged

2024-07-16 01:01 UTC, merged

2024-07-16 03:06 UTC, jimlin-sfgov commented
Oops, looks like we let this get through without proper coverage checks? I think we'll need to improve coverage in the related PR: https://github.com/SFDigitalServices/sf-dahlia-web/pull/2207

2024-07-16 15:24 UTC, chadbrokaw commented
> @chadbrokaw Looking forward to getting #2207 merged

Me too! Just got updated copy for the my applications page so should be good to go today 🙏