feat: DAH-2387: Adaptive password validation
SFDigitalServices/sf-dahlia-web pull request #2234
Opened 2024-08-07 16:23 UTC by chadbrokaw

[DAH-2387](https://sfgovdt.jira.com/browse/DAH-2387)

2024-08-07 21:48 UTC, tallulahkay commented on app/javascript/api/authApiService.ts
> +// export const updatePassword = async (
you can just delete this!

2024-08-07 21:49 UTC, tallulahkay commented on app/javascript/pages/account/PasswordFieldset.tsx
> +const instructionListItem = (
can you capitalize the beginning to match the patterns of the rest of the file

2024-08-07 21:59 UTC, tallulahkay requested changes
Looks rly good!! Two updates needed.
1. Validation state needs to reset after the password is submitted successfully 
<img width="1388" alt="Screenshot 2024-08-07 at 2 58 37 PM" src="https://github.com/user-attachments/assets/257717b1-d400-4ea5-83ce-5fbe5df4dc6f">

2. Validation state needs to be reset after the password is submitted but the old password doesn't match. (Do we need to show an adaptive error message saying old password doesn't match?)
<img width="1388" alt="Screenshot 2024-08-07 at 2 56 30 PM" src="https://github.com/user-attachments/assets/09408189-9a19-4179-8813-1bb1b33be129">

2024-08-08 16:49 UTC, chadbrokaw commented
> Looks rly good!! Two updates needed.
> 
> 1. Validation state needs to reset after the password is submitted successfully
> 
> <img alt="Screenshot 2024-08-07 at 2 58 37 PM" width="1388" src="https://private-user-images.githubusercontent.com/43218114/356006023-257717b1-d400-4ea5-83ce-5fbe5df4dc6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzU5MzgsIm5iZiI6MTcyMzEzNTYzOCwicGF0aCI6Ii80MzIxODExNC8zNTYwMDYwMjMtMjU3NzE3YjEtZDQwMC00ZWE1LTgzY2UtNWZiZTVkZjRkYzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE2NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmODllOWY3YjU0YzFmNDMxMjM2YjZhYmExM2ZhMWNjZDc4NjczNTkwNjU5YzNiODdhODM3OWUxMjYxZjU3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m3ZnnGgpizkgVq8xU8dun8tn4nFpDsZI44MVd0_3wCo">
> 2. Validation state needs to be reset after the password is submitted but the old password doesn't match. (Do we need to show an adaptive error message saying old password doesn't match?)
> 
> <img alt="Screenshot 2024-08-07 at 2 56 30 PM" width="1388" src="https://private-user-images.githubusercontent.com/43218114/356005321-09408189-9a19-4179-8813-1bb1b33be129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzU5MzgsIm5iZiI6MTcyMzEzNTYzOCwicGF0aCI6Ii80MzIxODExNC8zNTYwMDUzMjEtMDk0MDgxODktOWExOS00MTc5LTg4MTMtMWJiMWIzM2JlMTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE2NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OTQ4YzMxNjg5ZWZhMTgyNDU4MTgyMjI5OTE0ZDQxNjQwNGZjYjk2OTJkZjlmYjRlZThkODg1ZWEwZDFmODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7E_zeYCZbRLX76dlhSo_pk7jjh49pYt-hfmepuMnHVk">

Thank you for catching that! The validation should clear on submit now

2024-08-08 16:57 UTC, tallulahkay approved these changes
Amazing work!

2024-08-14 21:02 UTC, tallulahkay approved these changes

2024-08-14 21:32 UTC, merged