feat: DAH-2841 Double submit and already submitted modal
SFDigitalServices/sf-dahlia-web pull request #2395
Opened 2024-10-31 21:57 UTC by chadbrokaw

## Description

This PR adds support for the double submitted and already submitted modals.

## Jira ticket

https://sfgovdt.jira.com/browse/<JIRA TICKET NUMBER>

## Checklist before requesting review

### Version Control

- [ ] branch name begins with `angular` if it contains updates to Angular code
- [ ] branch name contains the Jira ticket number
- [ ] PR name follows `type: TICKET-NUMBER Description` format, e.g. `feat: DAH-123 New Feature`

### Code quality

- [ ] [the set of changes is small](https://google.github.io/eng-practices/review/developer/small-cls.html#what-is-small)
- [ ] all automated code checks pass (linting, tests, coverage, etc.)
- [ ] code irrelevant to the ticket is not modified e.g. changing indentation due to automated formatting
- [ ] if the code changes the UI, it matches the UI design exactly

### Review instructions

- [ ] instructions specify which environment(s) it applies to
- [ ] instructions work for PA testers
- [ ] instructions have already been performed at least once

### Request review

- [ ] PR has `needs review` label
- [ ] Use `Housing Eng` group to automatically assign reviewers, and/or assign specific engineers
- [ ] If time sensitive, notify engineers in Slack

2024-11-05 04:44 UTC, jimlin-sfgov requested changes
issue: the React modals are centered vertically on the page, which is different from the angular modals. Also, the button has underlined text, which is different from the angular modal.
![Screenshot 2024-11-04 at 2 50 49 PM](https://github.com/user-attachments/assets/789e1142-7c0a-4cdc-a78d-9dc9c8f1a200)
![Screenshot 2024-11-04 at 7 55 17 PM](https://github.com/user-attachments/assets/8079fc87-3187-49cb-99d5-d74d0b97793a)

2024-11-06 15:59 UTC, chadbrokaw commented on app/assets/javascripts/short-form/ShortFormApplicationController.js.coffee
> +          newUrl = "#{currentUrl}/my-applications?react=true"
I was wondering that. I think it is most likely redundant since we are checking if the flag is set to true beforehand. I removed it

2024-11-08 14:49 UTC, chadbrokaw commented
> issue: the React modals are centered vertically on the page, which is different from the angular modals. Also, the button has underlined text, which is different from the angular modal. ![Screenshot 2024-11-04 at 2 50 49 PM](https://private-user-images.githubusercontent.com/133722877/383009006-789e1142-7c0a-4cdc-a78d-9dc9c8f1a200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzc0ODMsIm5iZiI6MTczMTA3NzE4MywicGF0aCI6Ii8xMzM3MjI4NzcvMzgzMDA5MDA2LTc4OWUxMTQyLTdjMGEtNGNkYy1hNzhkLTlkYzljOGYxYTIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDQ2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjZhMGY4MTZkOTQ0N2VlNmQ3ZmVjOGJlZjI0NGU0Y2I2MmMyOWY5ZjRhNjJhZDczZDg5YTU5ODIyY2IzN2QwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pFU8nq95trGMQ0_Q9Ec5M6KRsVzoF2ZP2M_YlBVyAug) ![Screenshot 2024-11-04 at 7 55 17 PM](https://private-user-images.githubusercontent.com/133722877/383009026-8079fc87-3187-49cb-99d5-d74d0b97793a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzc0ODMsIm5iZiI6MTczMTA3NzE4MywicGF0aCI6Ii8xMzM3MjI4NzcvMzgzMDA5MDI2LTgwNzlmYzg3LTMxODctNDljYi05OWQ1LWQ3NGQwYjk3NzkzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDQ2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjJmYzg2ODQ2ZGJjYzE2YTlhZmVhNGI3ODcwZTA2N2E4ZWIyYWJhNGJlZmFiMjA4M2RiYjlkYzZlMDI0MDhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BENcy5HT-4ih2Pnil5yyX7fSllY3wS9RFII-SNLzDWg)

Thanks for flagging @jimlin-sfgov! I confirmed with Yindi that the new Dialog behavior is okay. We also tried to trigger the DoubleSubmit modal but we were not able to do so. We decided to leave the modal logic in the application anyway to document the behavior and protect the application if that event does happen. I added a comment to the code describing this decision

2024-11-08 17:15 UTC, jimlin-sfgov approved these changes
LGTM

2024-11-12 18:22 UTC, merged